AllCops:
  NewCops: enable

Style/MethodDefParentheses:
  Enabled: false

Layout/FirstArrayElementIndentation:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Style/Documentation:
  Enabled: false

Layout/LineEndStringConcatenationIndentation:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/PerlBackrefs:
  Enabled: false