AllCops:
  NewCops: enable

Style/MethodDefParentheses:
  Enabled: false

Layout/FirstArrayElementIndentation:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Style/Documentation:
  Enabled: false

Layout/LineEndStringConcatenationIndentation:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/PerlBackrefs:
  Enabled: false

Style/SymbolProc:
  Enabled: false

# Although I generally agree that these are a bad practice, we're making an exception in order
# to create a DSL
Style/ClassVars:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Layout/ArgumentAlignment:
  Enabled: false

Layout/ParameterAlignment:
  Enabled: false

Layout/BlockAlignment:
  Enabled: false

Layout/MultilineHashBraceLayout:
  Enabled: false

Layout/FirstHashElementIndentation:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Style/NestedParenthesizedCalls:
  Enabled: false